-- require('nvim-treesitter.configs').setup {
--   ensure_installed = "maintained",
--   highlight = {
--     enable = true,
--     additional_vim_regex_highlighting = true,
--   },
--   incremental_selection = {
--     enable = true,
--     keymaps = {
--       init_selection = "<cr>",
--       scope_incremental = "<cr>",
--       node_incremental = "<tab>",
--       node_decremental = "<s-tab>",
--     },
--   },
-- }
